import re
from playwright.sync_api import Page, expect
def test_example(page: Page) -> None:
    page.get_by_role("textbox", name="e.g. Global Filters").click()
    page.get_by_role("textbox", name="e.g. Global Filters").fill("Global Filters Section")
    page.get_by_role("button", name="Add Section").click()
    page.locator(".zeb-filter").first.click()
    page.locator("div").filter(has_text=re.compile(r"^Hierarchy$")).nth(2).click()
    page.locator(".d-flex.p-l-32").first.click()
    page.get_by_text("Team", exact=True).click()
    page.locator(".filter-values.d-flex.align-items-center.p-l-32.p-r-24 > .custom-checkbox-wrapper > .pointer").first.click()
    page.locator(".custom-checkbox-wrapper.overflow-hidden.d-flex.justify-content-center.m-r-8.pointer.white-background-color > .pointer").first.click()
    page.locator(".custom-checkbox-wrapper.overflow-hidden.d-flex.justify-content-center.m-r-8.pointer.white-background-color > .pointer").first.click()
    page.locator(".custom-checkbox-wrapper.overflow-hidden.d-flex.justify-content-center.m-r-8.pointer.white-background-color > .pointer").first.click()
    page.locator(".custom-checkbox-wrapper.overflow-hidden.d-flex.justify-content-center.m-r-8.pointer.white-background-color > .pointer").first.click()
    page.locator("div:nth-child(8) > .custom-checkbox-wrapper > .pointer").click()
    page.locator(".custom-checkbox-wrapper.overflow-hidden.d-flex.justify-content-center.m-r-8.pointer.white-background-color > .pointer").first.click()
    page.locator("#SideFilterproducthierarchyId").get_by_text("Department").click()
    page.locator(".custom-checkbox-wrapper.overflow-hidden.d-flex.justify-content-center.m-r-8 > .pointer").first.click()
    page.get_by_role("button", name="Apply Filters").click()
    page.locator(".aggrigate-panel > .custom-checkbox-wrapper > .pointer").click()
    page.get_by_role("button", name="Apply Filters").click()
    page.locator(".notification-circle").click()
    page.locator(".zeb-filter").first.click()
    page.get_by_role("textbox", name="e.g. Global Filters").click()
    page.get_by_role("textbox", name="e.g. Global Filters").fill("Complex Filters and Dropdown Filters")
    page.get_by_role("button", name="Add Section").click()
    page.locator(".dropdown-caret.p-l-16").first.click()
    page.locator(".d-flex.dropdown-option.align-items-center.p-v-5.p-l-32 > .d-flex").first.click()
    page.locator(".dropdown-caret.p-l-16").first.click()
    page.locator("#seasontype-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("#seasontype-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("#product-line-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("#product-line-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("#time-filterId > .wr-20 > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.get_by_role("button", name="Apply").click()
    page.get_by_role("textbox", name="e.g. Global Filters").click()
    page.get_by_role("textbox", name="e.g. Global Filters").fill("Monthly Trend Graph")
    page.get_by_role("button", name="Add Section").click()
    page.locator("svg").get_by_text("Actual Sales & ROY Fcst ($)").click()
    page.locator("svg").get_by_text("Sales Fcst Adjusted ($)", exact=True).click()
    page.get_by_text("GD Sales Fcst Adjusted ($)", exact=True).click()
    page.get_by_text("Non GD Sales Fcst Adjusted ($)").click()
    page.get_by_text("GD Sales Fcst Override ($)", exact=True).click()
    page.get_by_text("Non GD Sales Fcst Override ($)").click()
    page.locator("svg").get_by_text("TY Actual Sales ($)").click()
    page.locator("svg").get_by_text("System Sales Fcst ($)").click()
    page.get_by_text("GD Sales Fcst ($)", exact=True).click()
    page.get_by_text("Non GD Sales Fcst ($)").click()
    page.locator("svg").get_by_text("LY Sales ($)", exact=True).click()
    page.locator("svg").get_by_text("% Change vs LY").click()
    page.locator("svg").get_by_text("LLY Sales ($)").click()
    page.locator("svg").get_by_text("% Change vs LLY").click()
    page.locator(".ellipses > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.zeb-check").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".overflow-auto > div:nth-child(4)").click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").first.click()
    page.locator(".d-flex.flex-column.justify-content-center.font-size-10.align-items-center.checkbox-v2.m-r-10.deselected").click()
    page.locator(".ellipses > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".pointer.zeb-adjustments").first.click()
    page.get_by_text("Save Preference").click()
    page.get_by_role("textbox", name="e.g. Global Filters").click()
    page.get_by_role("textbox", name="e.g. Global Filters").fill("Monthly Summary")
    page.get_by_role("button", name="Add Section").click()
    page.locator("i").nth(3).click()
    page.locator("i").nth(5).click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator("div:nth-child(14) > .d-flex").click()
    page.locator("div:nth-child(13) > .d-flex").click()
    page.locator("div:nth-child(12) > .d-flex").click()
    page.locator("div:nth-child(11) > .d-flex").click()
    page.locator("div:nth-child(10) > .d-flex").click()
    page.locator("div:nth-child(9) > .d-flex").click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.locator(".d-flex.flex-column.justify-content-center").first.click()
    page.locator(".wr-20.font-weight-normal > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.locator("esp-card-component").filter(has_text="Monthly Summary All columns (").get_by_role("button").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("treeitem", name="Feb-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Mar-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Apr-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="May-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Jun-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Jul-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Aug-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (hidden)").check()
    page.locator("esp-card-component").filter(has_text="Monthly Summary All columns (").get_by_role("button").click()
    page.locator("div:nth-child(5) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.locator("div:nth-child(5) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    page.locator("div:nth-child(5) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Reset Preference").click()
    page.get_by_role("textbox", name="e.g. Global Filters").click()
    page.get_by_role("textbox", name="e.g. Global Filters").fill("Dept Summary")
    page.get_by_role("button", name="Add Section").click()
    page.locator(".ag-group-contracted > .ag-icon").first.click()
    page.locator(".ag-group-contracted > .ag-icon").first.click()
    page.locator(".ag-group-contracted > .ag-icon").first.click()
    page.locator(".ag-group-contracted > .ag-icon").first.click()
    page.locator(".ag-group-contracted > .ag-icon").first.click()
    page.locator(".ag-group-contracted > .ag-icon").first.click()
    page.locator(".ag-row-no-focus > .ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-column-first > .ag-cell-wrapper > .ag-group-contracted > .ag-icon").first.click()
    page.locator(".ag-row-no-focus > .ag-cell-value.ag-cell.ag-cell-not-inline-editing.ag-cell-normal-height.ag-column-first > .ag-cell-wrapper > .ag-group-contracted > .ag-icon").first.click()
    page.get_by_role("gridcell", name="Actual Sales & ROY Fcst ($)").nth(4).click()
    page.locator("esp-card-component").filter(has_text="Department Summary columns (0").get_by_role("button").click()
    page.get_by_role("checkbox", name="Toggle All Columns Visibility").uncheck()
    page.get_by_role("treeitem", name="Department Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Measure Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Jan-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Feb-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Mar-26 Column").get_by_label("Press SPACE to toggle").check()
    page.get_by_role("treeitem", name="Apr-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="May-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Jun-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Jul-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Aug-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Sep-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Oct-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("treeitem", name="Nov-26 Column").get_by_label("Press SPACE to toggle visibility (hidden)").check()
    page.get_by_role("checkbox", name="Press SPACE to toggle visibility (hidden)").check()
    page.locator("esp-card-component").filter(has_text="Department Summary columns (0").get_by_role("button").click()
    page.locator(".d-flex > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100 > .d-flex.align-items-center > .dropdown-caret").click()
    page.get_by_text("View 10 row(s)").click()
    page.locator("div:nth-child(3) > #preference-iconId > .legend-font > .multiselect-dropdown > .pointer").click()
    page.get_by_text("Save Preference").click()
    with page.expect_download() as download_info:
        page.locator("div:nth-child(2) > #export-iconId > .icon-color-toolbar-active").click()
    download = download_info.value
    page.get_by_role("gridcell", name="BRANDED").click(button="right")
    page.get_by_text("Drill down").click()
    page.locator("esp-bi-dimensional-grid").get_by_role("gridcell", name="Actual Sales & ROY Fcst ($)").click(button="right")
    page.locator("esp-bi-dimensional-grid").get_by_role("gridcell", name="Actual Sales & ROY Fcst ($)").click()
    page.locator(".ag-group-contracted > .ag-icon").click()
    page.locator(".d-flex > esp-multiselect-dropdown > .multiselect-dropdown > div > .w-100").click()
    page.get_by_text("View 20 row(s)").click()
    with page.expect_download() as download1_info:
        page.locator("div:nth-child(2) > #export-iconId > .icon-color-toolbar-active").click()
    download1 = download1_info.value
